package View;

import javax.swing.JButton;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author camilosar
 */
public class MainMenuView extends javax.swing.JPanel {

    /**
     * Creates new form MainMenuView
     */
    public MainMenuView() {
        initComponents();
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BotonLector = new javax.swing.JButton();
        BootonEscritor = new javax.swing.JButton();
        BotonSalir = new javax.swing.JButton();

        BotonLector.setText("Lector");
        BotonLector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonLectorActionPerformed(evt);
            }
        });

        BootonEscritor.setText("Escritor");

        BotonSalir.setText("Salir");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(BotonSalir))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(BotonLector)
                        .addGap(78, 78, 78)
                        .addComponent(BootonEscritor)))
                .addContainerGap(152, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(BotonLector)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BootonEscritor)
                        .addGap(88, 88, 88)))
                .addComponent(BotonSalir)
                .addGap(96, 96, 96))
        );

        getAccessibleContext().setAccessibleName("panel1");
    }// </editor-fold>//GEN-END:initComponents

    private void BotonLectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonLectorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonLectorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BootonEscritor;
    private javax.swing.JButton BotonLector;
    private javax.swing.JButton BotonSalir;
    // End of variables declaration//GEN-END:variables

    public JButton getBootonEscritor() {
        return BootonEscritor;
    }

    public JButton getBotonLector() {
        return BotonLector;
    }

    public JButton getBotonSalir() {
        return BotonSalir;
    }
}
